<a href="https://colab.research.google.com/github/analystmanu/ICP_2/blob/main/ICP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
Problem 1:

# Creating a class named "Employee" and a variable to count the number of employee.
class Employee:
    empCount = 0

# Next we will create a init constructor method for the name, family, salary, and department.
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1    # EMPLOYEE COUNT

# Next we will use a function named average_salary to calculate the avg salary by taking sum of salaries and dividing it by the number of employees.
    def average_salary(self):
        total_salary = 0
        total_salary += float(self.salary)
        avg = total_salary / Employee.empCount
        print('Average salary of the Employee:', avg)

# Next we will display the details of employees.
    def display(self):
        print('Employee Name:', self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)



# Inheriting fulltime employee class from employee
class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type

#FUNCTION TO DISPLAY EMPLOYEE DETAILS
    def display(self):
        print("Employee Name :", self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print('Type of Employment :', self.emp_type)



# Creating instances of Employee and Fulltime Employee
emp1 = Employee('Manu', '5', '25000000', 'Data scientist')
emp2 = Fulltime_Employee('Sharma', '4', '26000000', 'Data Analyst', 'Fulltime')
emp3 = Fulltime_Employee('Muhammad', '3', '27000000', 'full-stack Developer', 'Fulltime')

print("Count of the Employees :", emp1.empCount)
emp1.average_salary()
emp1.display()
emp2.display()
emp3.display()





Count of the Employees : 3
Average salary of the Employee: 8333333.333333333
Employee Name: Manu
Family Members: 5
Employee Annual Salary: 25000000
Department: Data scientist
Employee Name : Sharma
Family Members: 4
Employee Annual Salary: 26000000
Department: Data Analyst
Type of Employment : Fulltime
Employee Name : Muhammad
Family Members: 3
Employee Annual Salary: 27000000
Department: full-stack Developer
Type of Employment : Fulltime


Problem 2:

In [21]:
import numpy as np

# creating random vector of size 20 having only float in the range 1-20
random_vector = np.random.uniform(1, 20, 20)
print("Random Vector : \n", random_vector)

# Reshaping the array to 4x5
random_vector = random_vector.reshape(4,5)
print("after reshaping (4 by 5): \n", random_vector)

# replacing the max in each row by 0 (axis=1)

random_vector[np.arange(len(random_vector)), random_vector.argmax(1)] = 0
print("Replacing the maximum in each row : \n", random_vector)



Random Vector : 
 [ 4.71977523 11.51997449 12.93002983  8.88812471 11.46034017 14.6231766
  6.28700357  5.61730864 12.68215823 16.28552445 14.98804228 14.75542329
  2.12634538 18.30354006 18.87742073 17.75569965 19.27141547 16.43300079
 13.43438241 14.59050175]
after reshaping (4 by 5): 
 [[ 4.71977523 11.51997449 12.93002983  8.88812471 11.46034017]
 [14.6231766   6.28700357  5.61730864 12.68215823 16.28552445]
 [14.98804228 14.75542329  2.12634538 18.30354006 18.87742073]
 [17.75569965 19.27141547 16.43300079 13.43438241 14.59050175]]
Replacing the maximum in each row : 
 [[ 4.71977523 11.51997449  0.          8.88812471 11.46034017]
 [14.6231766   6.28700357  5.61730864 12.68215823  0.        ]
 [14.98804228 14.75542329  2.12634538 18.30354006  0.        ]
 [17.75569965  0.         16.43300079 13.43438241 14.59050175]]
